mysite/blog/urls.py
from django.urls import path
from . import views
from .views import send_email_view

app_name ='blog'

urlpatterns = [
  path('', views.PostListView.as_view(), name='post_list'),
  # path('', views.post_list, name='post_list'),
  path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
  path('<int:post_id>/share/', views.post_share, name='post_share'),
  path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
  path('send-email/', send_email_view, name='send_email'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('pro_user.urls', namespace='users')),
]

mysite/pro_user/urls.py
from django.urls import path
from . import views


app_name = "pro_user"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

class PublishedManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    object = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
      return reverse('blog:post_detail',
                     args=[self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug])

class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE,
                           related_name='comments')
  name = models.CharField(max_length=80)
  email = models.EmailField()
  body = models.TextField()
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  active = models.BooleanField(default=True)

  class Meta:
    ordering = ['-created']
    indexes = [models.Index(fields=['created']), ]

  def __str__(self):
    return f'Комментарий от {self.name} об {self.post}'

mysite/blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
  name = forms.CharField(max_length=25, label='Ваше имя')
  email = forms.EmailField()
  to = forms.EmailField(label='Кому')
  comments = forms.CharField(required=False,
                             widget=forms.Textarea,
                             label='Комментарии')

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['name', 'email', 'body']

mysite/pro_user/forms.py
from django import forms


class LoginUserForm(forms.Form):
    username = forms.CharField(label='логин',
                               widget=forms.TextInput(attrs={'class':'form-input'}))
    password = forms.CharField(label='пароль',
                               widget=forms.PasswordInput(attrs={'class':'form-input'}))

mysite/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.core.mail import send_mail
from .forms import EmailPostForm, CommentForm
from .models import Post
from  django.views.decorators.http import require_POST


# def post_list(request):
#   post_list = Post.published.all()
#   paginator = Paginator(post_list, 3)
#   page_number = request.GET.get('page', 1)
#   # posts = paginator.page(page_number)
#   try:
#     posts = paginator.page(page_number)
#
#   except PageNotAnInteger:
#     posts = paginator.page(1)
#
#   except EmptyPage:
#     posts = paginator.page(paginator.num_pages)
#   return render(request, 'blog/post/list.html', {'posts': posts})

def post_detail(request, year, month, day, post):
  # try:
  #   post = Post.published.get(id=id)
  # except Post.DoesNotExist:
  #   raise Http404('Пост не найден')
  post = get_object_or_404(Post,
                           status=Post.Status.PUBLISHED,
                           slug=post,
                           publish__year=year,
                           publish__month=month,
                           publish__day=day)
  #список активных комментариев к этому посту
  comments = post.comments.filter(active=True)
  #форма для комментирования пользователями
  form = CommentForm()
  return render(request, 'blog/post/detail.html',
                {'post': post,
                 'comments': comments,
                 'form': form})

class PostListView(ListView):
  queryset = Post.published.all()
  context_object_name = 'posts'
  paginate_by = 3
  template_name = 'blog/post/list.html'


def post_share(request, post_id):
  # извлечь пост по индефекатору id
  post = get_object_or_404(Post,
                           id=post_id,
                           status=Post.Status.PUBLISHED)

  send = False

  if request.method == "POST":
    #форма была передана на обработку
    form = EmailPostForm(request.POST)
    if form.is_valid():
      #поля формы успешно прошли валидацию
      cd = form.cleaned_data
      post_url = request.build_absolute_uri(post.get_absolute_url())
      subject = f"{cd['name']} рекомендует вам прочитать {post.title}"
      massage = f"Прочитать {post.title} at {post_url} {cd['name']} комментарии: {cd['comments']}"
      send_mail(subject, massage, 'evamilya@bk.ru', [cd['to']])
      send = True
      #... отправить электронное письмо

  else:
    form = EmailPostForm()
  return render(request, 'blog/post/share.html', {'post': post,
                                                      'form': form,
                                                      'send': send})

@require_POST
def post_comment(request, post_id):
  post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
  comment = None

  #комментарий был отправлен
  form = CommentForm(data=request.POST)
  if form.is_valid():
    #создать объект класса Comment, не сохраняя его в базе данных
    comment = form.save(commit=False)
    #назначить пост комментария
    comment.post = post
    #сохранить комментарий в базе данных
    comment.save()
  return render(request, 'blog/post/comment.html', {'post': post,
                                                    'form': form,
                                                    'comment': comment})


from django.core.mail import EmailMessage
from django.shortcuts import HttpResponse

def send_email_view(request):
    email = EmailMessage(
        subject='Внимание д/з',
        body='Это домашнее задание от 12 февраля 2024 года',
        from_email='Admin <evamilya@bk.ru>',
        to=['nadiamilyaeva@gmail.com', 'nadia.milyaeva@mail.ru'],
        )

    email.send()

    return HttpResponse('Письмо успешно отправлено!')

mysite/pro_user/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from pro_user.forms import LoginUserForm


def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('blog:post_list'))
    else:
        form = LoginUserForm()

    return render(request, 'users/login.html', {'form': form})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} {% endblock %}</title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<header>
  {% if user.is_authenticated %}
    <div class="us"> {{ user.username }} | <a href="{% url 'users:logout' %}">Выйти</a></div>
    {% else %}
    <div class="us"><a href="{% url 'users:login' %}">Войти</a> | <a href="#">Регистрация</a></div>
        {% endif %}
</div>
</header>
<body>
<div id="content">
  {% block content %} {% endblock %}
</div>

<div id="sidebar">
  <h2>Мой блог</h2>
  <p>Это мой блог</p>
</div>
</body>
</html>

mysite/blog/templates/blog/post/comment.html
{% extends 'blog/base.html' %}

{% block title %}Add a comment{% endblock %}

{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include 'blog/post/includes/comment_form.html' %}
{% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
  Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
<p>
  <a href="{% url 'blog:post_share' post.id %}">
  Share this post
  </a>
</p>
{% with comments.count as total_comments %}
<h2>
  {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
  <p class="info">
    Comment {{ forloop.counter }} by {{ comment.name }}
    {{ comment.created }}
  </p>
  {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments.</p>
{% endfor %}
{% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url 'blog:post_comment' post.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Add comment"></p>
</form>

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block title %}Мой блог{% endblock %}

{% block content %}
<h1>Мой блог</h1>
{% for post in posts %}
<h2>
  <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>

<p class="date">
  Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}

<!--{% include 'pagination.html' with page=posts %}-->
<!--&lt;!&ndash;используется для view функции представления&ndash;&gt;-->
<ul>
{% for group in user_groups %}
        <li>{{ group.name }}</li>
    {% empty %}
        <li>Вы не состоите ни в одной группе.</li>
    {% endfor %}
    </ul>
{% include 'pagination.html' with page=page_obj %}
<!--используется для класса представления-->

{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Поделиться публикацией {% endblock %}

{% block content %}
{% if send %}
      <h1>Письмо успешно отправлено</h1>
      <p>
        '{{ post.title }}' было успешно отправлено по {{ form.cleaned_data.to }}.
</p>
{% else %}
  <h1>Пост  '{{ post.title }}' отправляется </h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить письмо">
  </form>
{% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">

  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">предыдущая</a>
    {% endif %}

  <span class="current">
    страница {{ page.number }} из {{ page.paginator.num_pages }}
  </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">следующая</a>
    {% endif %}
  </span>
</div>

mysite/pro_user/templates/users/login.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Войти</button></p>

</form>

{% endblock %}

mysite/pro_user/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>